server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index olympiad-task-search.html;
    add_header Cache-Control "no-store" always;

    location = / {
        try_files /olympiad-task-search.html =404;
    }

    location ~ ^/tasks/[^/]+/?$ {
        try_files /olympiad-task-search.html =404;
    }

    location ~ "^/api/tasks/tasks(/[0-9a-fA-F-]{36})?$" {
        limit_except GET HEAD { deny all; }
        rewrite ^/api/tasks(/.*)$ $1 break;
        proxy_pass http://task-app:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location ~ ^/api/olympiads/(universities|subjects|olympiads/recommendations|universities/[0-9]+/programs|olympiads/[0-9]+/stages)$ {
        limit_except GET HEAD { deny all; }
        rewrite ^/api/olympiads(/.*)$ $1 break;
        proxy_pass http://olymp-app:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    location /api/ { return 404; }

    location / {
        try_files $uri =404;
    }
}
