# 1. Автоматический редирект с  HTTP на HTTPS
server {
    listen 80;
    server_name gazprompt.duckdns.org;
    return 301 https://$host$request_uri;
}

# 2. Основной HTTPS сервер
server {
    listen 443 ssl;
    server_name gazprompt.duckdns.org;

    ssl_certificate /etc/nginx/ssl/fullchain.cer;
    ssl_certificate_key /etc/nginx/ssl/gazprompt.duckdns.org.key;

    # Настройки безопасности SSL
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    root /usr/share/nginx/html;
    index index.html;
    add_header Cache-Control "no-store" always;

    location = /olympiad-home.html { return 301 /; }
    location = /olympiad-onboarding.html { return 301 /olympiads; }
    location = /olympiad-after-onboarding.html { return 301 /olympiads; }
    location = /olympiad-task-search.html { return 301 /tasks; }
    location = /olympiad-task-solve.html { rewrite ^ /practice? permanent; }
    location = /olympiad-statistics.html { return 301 /statistics; }
    location = /olympiad-community.html { return 301 /communities; }

    location /webhook {
        proxy_pass http://task-app:8000/webhook;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /api/max/ {
        proxy_pass http://task-app:8000/api/max/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location ~ "^/api/tasks/(tasks(/[0-9a-fA-F-]{36}(/solutions)?)?|olympiads)$" {
        limit_except GET HEAD { deny all; }
        rewrite ^/api/tasks(/.*)$ $1 break;
        proxy_pass http://task-app:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme; # Важно для корректного HTTPS на бэкенде
    }

    location ~ ^/api/olympiads/(universities|subjects|olympiads/recommendations|universities/[0-9]+/programs|olympiads/[0-9]+(/stages)?)$ {
        limit_except GET HEAD { deny all; }
        rewrite ^/api/olympiads(/.*)$ $1 break;
        proxy_pass http://olymp-app:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme; # Важно для корректного HTTPS на бэкенде
    }

    location /api/ { return 404; }

    location /assets/ { try_files $uri =404; }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
